### ISSUE TITLE
patch for netgen

### ISSUE THREAD

**Issue by looooo** [vejmarie/Netgen#1]
Hi,
thanks for your efforts to port netgen to latest occ.
I have tried to create a patch file from this branch for the origin netgen, but failed. Maybe you have the possibility to do so... or maybe you can point me to all the changes you have made. Most of them are already in the initial commit, so not visible for me. 

if you have set the origin netgen-repo as remote locally you can try this to produce a patch file:

``` bash
git format-patch origin/HEAD  --stdout > output-file.patch
```

thanks and nice regards
Lorenz

**Comment by vejmarie** [comment]
Hi looooo sorry for my late replied I was focused on a few bugs with FreeCAD. I will generate your patch file during the week-end ;). I build this tree using the patch directly sorry about that, there is currently no way to track the changes, as the initial import is the working version.

**Comment by vejmarie** [comment]
@looooo I have created a new repo netgen_5.3.1_occt7 which contains 2 commit. Initial is netgen 5.3.1 source code. Second commit is the few patches needed to compile with OCCT7

**Comment by vejmarie** [comment]
@looooo have you been able to clone the repo ?

**Comment by looooo** [comment]
Thanks a lot. For the cmake install of netgen I needed some more changes (see this patch  [file](https://github.com/looooo/FreeCAD_Conda/blob/master/netgen/netgen.patch)). If it is ok to you I will try to add the cmake patches to your repo with a pr. Maybe we should also try to make the changes not breaking the build with older occ version? Something like this:

```
#IF OCC_VERSION >= 7
...
#ELSE OCC_VERSION >= 7
...
#ENDIF OCC_VERSION >= 7
```

This way we can send patches directly to netgen...

**Comment by vejmarie** [comment]
Hi, I agree, just need some time to make it happen :(. Let me check that during the week-end.

**Comment by vejmarie** [comment]
No problem to get a PR from you on this repo !

**Comment by looooo** [comment]
Do you know the proper way to check OCC version in netgen. I have tried to do it the same way as it is done in freecad  `#if OCC_VERSION_HEX < 0x070000` but this doesn't work for me.

**Comment by looooo** [comment]
There was missing the version header... With this addition it works now:

```
#ifndef _Standard_Version_HeaderFile
#include <Standard_Version.hxx>
#endif
```

I have now created a [patch-file](https://github.com/looooo/FreeCAD_Conda/blob/master/netgen/netgen.patch) for the git master of netgen which should work with occt7. But I don't know if it is compatible with the netgen version you have used  (5.3.1).  Is there a reason why you choose an older version?

**Comment by vejmarie** [comment]
I think this was the latest version supported by FreeCAD by the time I started the work to port FreeCAD to OCCT 7 and SMESH 7.7.1 ;)
